<?php
$cant_neighb=106;
$Barrs=array(
    "Manizales",
    "Alcazares",
    "Alferez Real",
    "Alta Leonora",
    "Alta Suiza",
    "Alto Persia",
    "Alto Prado",
    "Alto Tablazo",
    "Altos de Granada",
    "Aranjuez",
    "Arrayanes",
    "Avanzada",
    "Baja Leonora",
    "Bajo Persia",
    "Bajo Prado",
    "Bajo Tablazo",
    "Bengala",
    "Bosques del Norte",
    "Camilo Torres",
    "Caminos de la cumbre",
    "Campoamor",
    "Campohermoso",
    "Centenario",
    "Centro",
    "Cervantes",
    "Chipre",
    "Colinas",
    "Colón",
    "Comuneros",
    "Cuchilla del Salado",
    "Cumbre",
    "El Bosque",
    "El Camping",
    "El Caribe",
    "El Carmen",
    "El Castilla",
    "El Gonzales",
    "El Guamal",
    "El Nevado",
    "El Paraiso",
    "El Peñon",
    "El Porvenir",
    "Enea",
    "Estambul",
    "Eucaliptus",
    "Fatima",
    "Galán",
    "Jesus de la Buena Esperanza",
    "Jose Restrepo",
    "Kenedy",
    "La Arboleda",
    "La Argentina",
    "La Carola",
    "La Francia",
    "La Galeria",
    "La Isabela",
    "La Isla",
    "La Linda",
    "La Pelusa",
    "La Sultana",
    "La Toscana Camino de Dios",
    "La Union",
    "Las Americas",
    "Las Delicias",
    "Liborio",
    "Linares",
    "Lleras",
    "Los Agustinos",
    "Los Andes",
    "Los Cambulos",
    "Los Cedros",
    "Lusitania Alta",
    "Lusitania Baja",
    "Malhabar",
    "Malteria",
    "Marmato",
    "Milan",
    "Minitas",
    "Nogales",
    "Palmas de Chipre",
    "Panamericana",
    "Panorama",
    "Peralonso",
    "Pio 12",
    "Puertas del sol",
    "Quinta Hispania",
    "Ranchitos",
    "Samaria",
    "San Antonio",
    "San Cayetano",
    "San Ignacio",
    "San Jorge",
    "San Jose",
    "San Sebastián",
    "Santos",
    "San Vicente",
    "Sinai",
    "Solferino",
    "Solidaridad",
    "Villa Cafe",
    "Villa Carmenza",
    "Villa Hermosa",
    "Villa Luz",
    "20 de Julio",
);

?>