<?php
$cant_neighb=174;
$Barrs=array(
    "Manizales",
    "",
    "Alcazares",
    "Alferez Real",
    "Alta Leonora",
    "Alta Suiza",
    "Alto Persia",
    "Alto Prado",
    "Alto Tablazo",
    "Altos de Granada",
    "Aranjuez",
    "Arrayanes",
    "Avanzada",
    "Baja Leonora",
    "Bajo Persia",
    "Bajo Prado",
    "Bajo Tablazo",
    "Bengala",
    "Bosques del Norte",
    "Camilo Torres",
    "Caminos de la cumbre",
    "Campoamor",
    "Campohermoso",
    "Centenario",
    "Centro",
    "Cervantes",
    "Chipre",
    "Colinas",
    "Colón",
    "Comuneros",
    "Cuchilla del Salado",
    "Cumbre",
    "El Bosque",
    "El Camping",
    "El Caribe",
    "El Carmen",
    "El Castilla",
    "El Gonzales",
    "El Guamal",
    "El Nevado",
    "El Paraiso",
    "El Peñon",
    "El Porvenir",
    "Enea",
    "Estambul",
    "Eucaliptus",
    "Fatima",
    "Galán",
    "Jesus de la Buena Esperanza",
    "Jose Restrepo",
    "Kenedy",
    "La Arboleda",
    "La Argentina",
    "La Carola",
    "La Francia",
    "La Galeria",
    "La Isabela",
    "La Isla",
    "La Linda",
    "La Pelusa",
    "La Sultana",
    "La Toscana Camino de Dios",
    "La Union",
    "Las Americas",
    "Las Delicias",
    "Liborio",
    "Linares",
    "Lleras",
    "Los Andes",
    "Los Cambulos",
    "Los Cedros",
    "Lusitania Alta",
    "Lusitania Baja",
    "Malhabar",
    "Malteria",
    "Marmato",
    "Milan",
    "Minitas",
    "Nogales",
    "Palmas de Chipre",
    "Panamericana",
    "Panorama",
    "Peralonso",
    "Pio 12",
    "Puertas del sol",
    "Quinta Hispania",
    "Ranchitos",
    "Samaria",
    "San Antonio",
    "San Cayetano",
    "San Ignacio",
    "San Jorge",
    "San Jose",
    "San Sebastián",
    "Santos",
    "San Vicente",
    "Sinai",
    "Solferino",
    "Solidaridad",
    "Villa Cafe",
    "Villa Carmenza",
    "Villa Hermosa",
    "Villa Luz",
    "20 de Julio",
    //Villa Maria
    "Villa Maria (Villa Maria)",
    "Altamira (Villa Maria)",
    "Alto del Portón (Villa Maria)",
    "Altos de la Virgen (Villa Maria)",
    "Altos de Monserrate (Villa Maria)",
    "Altos del Portal (Villa Maria)",
    "Andalucía (Villa Maria)",
    "Arrayanes (Villa Maria)",
    "Balcones de la Villa (Villa Maria)",
    "Bellavista (Villa Maria)",
    "Bomberos (Villa Maria)",
    "Calamar (Villa Maria)",
    "Calima (Villa Maria)",
    "Centro (Villa Maria)",
    "Coloya (Villa Maria)",
    "CRC (Villa Maria)",
    "El Crucero (Villa Maria)",
    "El Guadual (Villa Maria)",
    "El Palmar (Villa Maria)",
    "El Portal (Villa Maria)",
    "Gerardo Arias (Villa Maria)",
    "Guayacanes (Villa Maria)",
    "Jorge Eliécer Gaitán (Villa Maria)",
    "La Alameda (Villa Maria)",
    "La Aldea (Villa Maria)",
    "La Capilla (Villa Maria)",
    "La Floresta (Villa Maria)",
    "La Floresta 2(Villa Maria)",
    "La Florida (Villa Maria)",
    "La Porteña (Villa Maria)",
    "La Pradera (Villa Maria)",
    "Los Patios (Villa Maria)",
    "Los Vagones (Villa Maria)",
    "Miraflores (Villa Maria)",
    "Miraflores II (Villa Maria)",
    "Molinos (Villa Maria)",
    "Nereidas (Villa Maria)",
    "Nuevos Horizontes (Villa Maria)",
    "Obrero (Villa Maria)",
    "Pinares del Rio (Villa Maria)",
    "Polideportivo (Villa Maria)",
    "Popular (Villa Maria)",
    "Portales de Capri (Villa Maria)",
    "San Diego (Villa Maria)",
    "San Martín (Villa Maria)",
    "San Miguel (Villa Maria)",
    "Santa Ana (Villa Maria)",
    "Santa Luisa (Villa Maria)",
    "Santa María de la Colina (Villa Maria)",
    "Turín (Villa Maria)",
    "Urapanes (Villa Maria)",
    "Vereda la Floresta (Villa Maria)",
    "Villa Beatriz (Villa Maria)",
    "Villa Diana (Villa Maria)",
    "Villa Fernando (Villa Maria)",
    "Villa I (Villa Maria)",
    "Villa II (Villa Maria)",
    "Villa III (Villa Maria)",
    "Villa IV (Villa Maria)",
    "Villa V (Villa Maria)",
    "Villa Jardín (Villa Maria)",
    "Villa Julia (Villa Maria)",
    "Villa Mana (Villa Maria)",
    "Villa Salón (Villa Maria)",
);

?>