<?php
$IdCli=$result->IdCli;
$NameCli=$result->NameCli;
$document_cli=$result->document;
$Barrio=$result->Barrio;
$Direccion=$result->Direccion;
$maps=$result->maps;
$TelCli=$result->TelCli;
$email_cli=$result->email;
$Visita=$result->Visita;
$hour=$result->hour;
$frequency=$result->frequency;
$RutaC=$result->Ruta;
?>