<?php
$IdCli=$result->IdCli;
$NameCli=$result->NameCli;
$Barrio=$result->Barrio;
$Direccion=$result->Direccion;
$maps=$result->maps;
$TelCli=$result->TelCli;
$Frec=$result->Frecuencia;
$Visita=$result->Visita;
$hour=$result->hour;
$RutaC=$result->Ruta;
?>